services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: unless-stopped
