version: "3.8"

services:
  waf:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "81:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    mem_limit: 512m
    cpus: 2

  web:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    mem_limit: 512m
    cpus: 2